service: votacion-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

package:
  individually: true

functions:
  getByORM:
    handler: src/functions/getPorSP.handler
    events:
      - http:
          path: /api/pruebaSP
          method: post
          authorizer:
            name: authorizerFunction
            type: token

  vote:
    handler: src/functions/vote.handler
    events:
      - http:
          path: /api/vote
          method: post
          authorizer:
            name: authorizerFunction
            type: token
  
  listVotes:
    handler: src/functions/listVotes.handler
    events:
      - http:
          path: /api/listVotes
          method: post
          authorizer:
            name: authorizerFunction
            type: token

  invest:
    handler: src/functions/invest.handler
    events:
      - http:
          path: /api/invest
          method: post
          authorizer:
            name: authorizerFunction
            type: token
  
  authorizerFunction:
    handler: src/functions/authMiddleware.handler


