service: votacion-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

package:
  individually: true

functions:
  getByORM:
    handler: src/functions/getByORM.handler
    events:
      - http:
          path: /api/providers/orm
          method: get

  vote:
    handler: src/functions/vote.handler
    events:
      - http:
          path: /api/vote
          method: post

  invest:
    handler: src/functions/invest.handler
    events:
      - http:
          path: /api/invest
          method: post
          authorizer:
            name: authorizerFunction
            type: request

  authorizerFunction:
    handler: src/functions/auth.handler


