service: votacion-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x

plugins:
  - serverless-offline

package:
  individually: true

functions:
  getByORM:
    handler: src/functions/getPorSP.handler
    events:
      - http:
          path: /api/pruebaSP
          method: post
          authorizer:
            name: authorizerFunction
            type: token
  
  invest:
    handler: src/functions/invest.handler
    events:
    - http:
        path: /api/invest
        method: post
        authorizer:
          name: authorizerFunction
          type: token

  distributeDividends:
    handler: src/functions/distributeDividends.handler
    events:
    - http:
        path: /api/distributeDividends
        method: post
        authorizer:
          name: authorizerFunction
          type: token

  vote:
    handler: src/functions/vote.handler
    events:
      - http:
          path: /api/vote
          method: post
          authorizer:
            name: authorizerFunction
            type: token
  
  listVotes:
    handler: src/functions/listVotes.handler
    events:
      - http:
          path: /api/listVotes
          method: post
          authorizer:
            name: authorizerFunction
            type: token

  comment:
    handler: src/functions/comment.handler
    events:
      - http:
          path: /api/comment
          method: post
          authorizer:
            name: authorizerFunction
            type: token
  
  configureVoting:
    handler: src/functions/configureVoting.handler
    events:
      - http:
          path: /api/configureVoting
          method: post
          authorizer:
            name: authorizerFunction
            type: token

  createUpdateProp:
    handler: src/functions/createUpdateProp.handler
    events:
      - http:
          path: /api/createUpdateProp
          method: post
          authorizer:
            name: authorizerFunction
            type: token

  revisarPropuesta:
    handler: src/functions/proposalReview.handler
    events:
      - http:
          path: /api/revisarPropuesta
          method: post
          authorizer:
            name: authorizerFunction
            type: token
  
  authorizerFunction:
    handler: src/functions/authMiddleware.handler


